### ISSUE TITLE
Removing show from SR dont remove show from trakt and also don't remove episodes from watchlist

### ISSUE THREAD

**Issue by fernandog** [SickRage/old-sickrage-issues#184]
as we talked

**Comment by miigotu** [comment]
It isnt supposed to remove your show completely from trakt. It stays in the collection, and the watch list so you dont lose track of shit you watched.

**Comment by OmgImAlexis** [comment]
@miigotu it should really remove it from your collection as trakt treats that as the shows you actually have, not the shows you had but deleted.

**Comment by yongbi85** [comment]
I'm sorry for bumping this but I agree it shouldnt remove it from collection but it should really remove it from watchlist.
I add show to my watchlist so that sickrage will sync with trakt and automatically grab the new series i want to watch.
I even checked the option : delete whole serie from watchlist once an episode is downloaded but it still stays in the trakt watchlist.
It is annoying because i move the series that are ended to another source in Kodi so when i remove them from sickrage, after a time it will add it back and start downloading the serie again... Which consequently messes up kodi library.
Can't you modify the way trakt and SR sync works ?
For example if a show exists in watchlist and not in SR ==> add it to SR and delete the show from watchlist.
Or at least offer an option that would do that.
For example an easy way to do that would be :
Retrieve tvshows watchlist if it exists in SR library delete the show season and episodes from trakt watchlist, if it doesnt exist add the show to SR then delete it from watchlist
