### ISSUE TITLE
Discuss: API v2 development

### ISSUE THREAD

**Issue by labrys** [SickRage/old-sickrage-issues#99]
This is issue is to discuss changes and features to add to the SR API v2.  It will also serve as a completion checklist towards the APIv2 milestone.

**Comment by labrys** [comment]
*reserved for future information*

**Comment by labrys** [comment]
*reserved for future information*

**Comment by labrys** [comment]
*reserved for future information*

**Comment by OmgImAlexis** [comment]
Everything that currently uses getMeta needs to be converted to an API call so we can get rid of that hack.

**Comment by stvkno** [comment]
Where's the API located on this repo?

**Comment by duramato** [comment]
@stvkno you ve got the api builer from within SR,with everything explained at /apibuilder ie `localhost:8081/apibuilder`

**Comment by felipesalomao** [comment]
Actually have only 1 api for subtitles scan:
cmd=episode.subtitlesearch&indexerid=247897&season=1&episode=3
It scan for new subtitle of determined tv show / season / epsode number

But i think that miss more 2 APIs:

Need some API that is able to return all tv shows / season / epsodes that is missing subtitle (manage missed subtitles)
And Also another API that is able to scan complete season or TV Show (All Seasons) (not only determined epsode) and also API that can scan all Missed Subtitles..

With this i could make script to monitor subtitle released subs in real time and if any tv show epsode is released, call subtitle scan in SR.. This would reduce from 1 hour to real time download in SR.. I would make external script, but if anyone need, i could share.. What you think about it @fernandog ?

**Comment by OmgImAlexis** [comment]
@felipesalomao by the way those are called endpoints, not APIs. :stuck_out_tongue_winking_eye:

**Comment by felipesalomao** [comment]
Hehe, Thanks for info.. I am not propper  developer.. Just a curious.. Have those new endpoints would be Great !

**Comment by pyrodex** [comment]
The SickRage API call for show exposes a good deal of existing data for the show which is great! I noticed in my leveraging the API for my own project it doesn't expose the Scene Exception field which helpful for what I am doing. Could this be added please? Thanks!

**Comment by MGaetan89** [comment]
Something that was ask for my app (https://github.com/MGaetan89/ShowsRage/issues/41): check server status from within the mobile app (ie. the data that are displayed in `/home/status/`).

-----

Change the URLs to be more RESTful. Some examples:
- `GET /api/v2/shows` -> Get the list of shows
- `GET /api/v2/show/{id}` -> Get the detail of a specific show
- `POST /api/v2/show` + JSON body -> Add a new show
- `PUT /api/v2/show/{id}` + JSON body -> Update an existing show
- `DELETE /api/v2/show/{id}` -> Delete an existing show
- The API builder can stay in `/apibuilder`

-----

Remove the wrapper around the JSON response. Instead of returning:
```json
{
    "data": {
        // The data
    },
    "message": "",
    "result": "success"
}
```

Simply return:
```json
{
    // The data
}
```

-----

Use HTTP status code to notify when something goes wrong. For example, when requesting a show that does not exist, use HTTP code 404.

**Comment by OmgImAlexis** [comment]
@MGaetan89 maybe we could also require `/api/internal/...` to have an active session so there wouldn't be a need for an API token for them? This would also mean that it couldn't be used outside of the webui.

**Comment by MGaetan89** [comment]
We can simply use the webUI session for the `/api/internal/...` calls, yes.

**Comment by Hellowlol** [comment]
I like the wrapper around the data. Makes handling easier imo

**Comment by labrys** [comment]
@Hellowlol we could potentially support both

**Comment by OmgImAlexis** [comment]
Another thing I'd like added is an endpoint for reporting js errors. We can then send all console errors to that endpoint and log them in Sickrage, that would help with reporting js issues that we miss.

**Comment by labrys** [comment]
@OmgImAlexis Added to the list

**Comment by rootwyrm** [comment]
Can you please add a naked API call to regenerate the API key? This would be very helpful for [container deployment](https://github.com/rootwyrm/lxc-media), since a default configuration needs to be provided to turn SSL on by default. 

Basically should do nothing more than call to `helpers.generateApiKey` - for security reasons it should probably only return OK/ERR and not the actual API key. (An authorized user should be able to retrieve it via WebUI or config.ini.) Perhaps `POST api/v2/srcfg/regenerateApiKey`?

**Comment by OmgImAlexis** [comment]
@rootwyrm wouldn't that be kind of an issue considering people could just find your Sickrage IP and then send a request to invalidate your current apiKey?

**Comment by Hellowlol** [comment]
Simple solution would be to require username and password if auth is active, if it isnt simply return new apikey.

**Comment by labrys** [comment]
@OmgImAlexis Im okay with this to some degree as the plan is to have different authorization levels based on user, possibly require and admin key or user/name password auth for this or possibly just allow for restircted access or something.  However, I don't see why this should be allowed without a valid apikey or user/password auth.  Final implementation details and/or decision on whether to include the feature can be decided as we get closer to development.  Also the current SickBeard API and SickRage UI both expose the API key directly so anyone with access to SickRage can currently see/generate new keys.
